<?php


namespace ronashdkl\kodCms\widgets\slider;


use ronashdkl\kodCms\modules\admin\viewModels\SliderModel;
use yii\base\Widget;
use yii\helpers\VarDumper;
use yii\web\View;

class SliderWidget extends Widget
{
    public $admin=false;
    public $width =null;
    public $selectorId = '#lbp-slider';

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $model = new SliderModel();

        if($this->admin){
            $this->getView()->registerAssetBundle(SliderAsset::className());
            return $this->render('slider-admin', ['images' => $model->getMedia(),'width'=>$this->width]);

        }
        $images = $model->getMedia();
        if($images==null){
            return null;
        }

       return $this->render('slider', ['images' =>$images ]);
    }
}
