<?php

namespace ronashdkl\kodCms\actions;


use ronashdkl\kodCms\models\post\PostEnquiry;

use ronashdkl\kodCms\modules\admin\models\Post;
use yii\base\Action;

use yii\helpers\Html;
use yii\web\NotFoundHttpException;

class EnquiryAction extends Action
{
    public $uniqueId = 'enquiry';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function runWithParams($params)
    {
        $post = Post::find()->where(['id' => $params['id']]);
        if (!$post->exists()) {
            throw new NotFoundHttpException();
        }
        $post = $post->one();
        $model = new PostEnquiry();
        $model->post_id = $post->id;
        if($model->load(\Yii::$app->request->post()) && $model->save()){
            $this->controller->return['title'] = $post->title;
            $this->controller->return['content'] = \Yii::t('site','Thank you for your intrest. We will contact you soon');
            $this->controller->return['footer'] =Html::button('Close', ['class' => 'btn btn-danger pull-left', 'data-dismiss' => "modal"]);
            return $this->controller->send();

        }
        $this->controller->return['title'] = $post->title;
        $this->controller->return['content'] = $this->controller->renderAjax('enquiry', ['model' => $model]);
        $this->controller->return['footer'] =Html::button('Close', ['class' => 'btn btn-danger pull-left', 'data-dismiss' => "modal"]).Html::button('Send', ['class' => 'btn btn-primary pull-right', 'type'=>'submit']);

        return $this->controller->send();
    }
}