<?php

namespace ronashdkl\kodCms\actions;

use ronashdkl\kodCms\modules\admin\models\Newsletter;
use yii\base\Action;
use yii\helpers\VarDumper;

class SubscribeAction extends Action
{
    public $uniqueId = 'subscribe';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function runWithParams($params)
    {
        if(isset($params['email']) && $params['email']!=null){
            $newsL = new Newsletter();
            $newsL->email = $params['email'];
           if($newsL->save()){
               return  \Yii::t('site',"Thank you for subscribing our newsletter!");
           }else{
               return $newsL->getFirstError('email');
           }
        }
        return $this->controller->send();
    }
}