<?php


namespace ronashdkl\kodCms\controllers;


use ronashdkl\kodCms\models\post\PostWidgetModel;
use ronashdkl\kodCms\modules\admin\models\Post;

use ronashdkl\kodCms\widgets\BreadCrumbWidget;
use ronashdkl\kodCms\widgets\PageContentWidget;
use ronashdkl\kodCms\widgets\PageMenuWidget;
use ronashdkl\kodCms\widgets\sections\about\AboutListSectionWidget;
use ronashdkl\kodCms\widgets\sections\header\HeaderWidget;
use ronashdkl\kodCms\widgets\sections\methodologies\MethodologiesSectionWidget;
use ronashdkl\kodCms\widgets\sections\services\ServicesSectionWidget;
use ronashdkl\kodCms\widgets\sections\top\TopHeaderWidget;
use ronashdkl\kodCms\widgets\slider\SliderWidget;
use ronashdkl\kodCms\widgets\sliders\holiday\HolidaySliderWidget;
use ronashdkl\kodCms\widgets\WidgetList;
use Codeception\PHPUnit\Constraint\Page;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PageController extends Controller
{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }



    public function actionIndex($slug)
    {

        $model = $this->findModel($slug);

       $this->view->title = $model->title;
       $images = $model->getImages();
       if($images!=null){
           $count = count($images);
           $this->view->params['page_image'] = $model->getImages()[rand(0,$count-1)];
       }


        \Yii::$app->appData->registerPageWidget();


        return $this->renderContent(PageContentWidget::widget(['model' => $model]));
    }

    protected function findModel($slug)
    {
        $model = Post::find()->where(['slug' => $slug])->published();
        if ($model->exists()) {
            return $model->one();
        } else {
            throw new NotFoundHttpException('Sorry! Requested page not found!', '404');
        }
    }
}
