<?php
namespace ronashdkl\kodCms\components;

use yii\web\Controller;

class PluginController extends Controller
{
public function init()
{
    parent::init(); // TODO: Change the autogenerated stub
}
}