<?php


namespace ronashdkl\kodCms\models\service;


use ronashdkl\kodCms\components\FieldConfig;
use ronashdkl\kodCms\models\ListModel;
use yii\base\Model;
use yii\helpers\ArrayHelper;

/**
 * Class AboutListModel
 * @property string $text
 * @package ronashdkl\kodCms\models\service
 */
class ServiceListModel extends ListModel
{

    public $name;
    public $summary;
    public $image;
    public $icon;
    public $url;
    public $display;
    public function rules()
    {

        return ArrayHelper::merge(parent::rules(), [
            ['image', 'string'],
            ['icon', 'string'],
            ['name', 'required'],
            ['url', 'string'],
            ['summary', 'required'],
            ['display', 'required'],
        ]);

    }

    public function formTypes()
    {
        return [
            'name' => [
                // 'value' => $this->text,
                'type' => FieldConfig::INPUT,
            ],

            'url' => [
                // 'value' => $this->text,
                'type' => FieldConfig::INPUT,
            ],

            'summary' => [
                // 'value' => $this->text,
                'type' => FieldConfig::CKEDITOR,
            ],
            'image' => [
                // 'value' => $this->text,
                'type' => FieldConfig::IMAGE,
            ],
            'icon' => [
                // 'value' => $this->text,
                'type' => FieldConfig::ICON,
            ],
            'display' => [
                // 'value' => $this->text,
                'type' => FieldConfig::RADIO,
                'data'=>['image'=>'Image','icon'=>'Icon']
            ]
        ];
    }

    public  function displayAttributes()
    {
        return  ['name','image'];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }
}
